services:
  ws-server-en:
    build:
      dockerfile: /src/main/docker/Dockerfile.jvm
    networks:
      - backend

  ws-server-us:
    build:
      dockerfile: /src/main/docker/Dockerfile.jvm
    networks:
      - backend

  load-balancer:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
networks:
  backend:
    external: true